// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkOperate int32

const (
	NetworkOperate_Delay NetworkOperate = 0
	NetworkOperate_Loss  NetworkOperate = 1
)

var NetworkOperate_name = map[int32]string{
	0: "Delay",
	1: "Loss",
}

var NetworkOperate_value = map[string]int32{
	"Delay": 0,
	"Loss":  1,
}

func (x NetworkOperate) String() string {
	return proto.EnumName(NetworkOperate_name, int32(x))
}

func (NetworkOperate) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type ErrorType int32

const (
	ErrorType_UnknownError      ErrorType = 0
	ErrorType_InProcessError    ErrorType = 1
	ErrorType_NoError           ErrorType = 2
	ErrorType_NotInProcessError ErrorType = 3
	ErrorType_UnMatchIdError    ErrorType = 4
)

var ErrorType_name = map[int32]string{
	0: "UnknownError",
	1: "InProcessError",
	2: "NoError",
	3: "NotInProcessError",
	4: "UnMatchIdError",
}

var ErrorType_value = map[string]int32{
	"UnknownError":      0,
	"InProcessError":    1,
	"NoError":           2,
	"NotInProcessError": 3,
	"UnMatchIdError":    4,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type Separation struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Flag                 string   `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Separation) Reset()         { *m = Separation{} }
func (m *Separation) String() string { return proto.CompactTextString(m) }
func (*Separation) ProtoMessage()    {}
func (*Separation) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Separation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Separation.Unmarshal(m, b)
}
func (m *Separation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Separation.Marshal(b, m, deterministic)
}
func (m *Separation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Separation.Merge(m, src)
}
func (m *Separation) XXX_Size() int {
	return xxx_messageInfo_Separation.Size(m)
}
func (m *Separation) XXX_DiscardUnknown() {
	xxx_messageInfo_Separation.DiscardUnknown(m)
}

var xxx_messageInfo_Separation proto.InternalMessageInfo

func (m *Separation) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Separation) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Separation) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type NetworkOperator struct {
	Operate              NetworkOperate `protobuf:"varint,1,opt,name=operate,proto3,enum=pb.NetworkOperate" json:"operate,omitempty"`
	Probability          int32          `protobuf:"varint,2,opt,name=probability,proto3" json:"probability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NetworkOperator) Reset()         { *m = NetworkOperator{} }
func (m *NetworkOperator) String() string { return proto.CompactTextString(m) }
func (*NetworkOperator) ProtoMessage()    {}
func (*NetworkOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *NetworkOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkOperator.Unmarshal(m, b)
}
func (m *NetworkOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkOperator.Marshal(b, m, deterministic)
}
func (m *NetworkOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkOperator.Merge(m, src)
}
func (m *NetworkOperator) XXX_Size() int {
	return xxx_messageInfo_NetworkOperator.Size(m)
}
func (m *NetworkOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkOperator.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkOperator proto.InternalMessageInfo

func (m *NetworkOperator) GetOperate() NetworkOperate {
	if m != nil {
		return m.Operate
	}
	return NetworkOperate_Delay
}

func (m *NetworkOperator) GetProbability() int32 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.NetworkOperate", NetworkOperate_name, NetworkOperate_value)
	proto.RegisterEnum("pb.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterType((*Separation)(nil), "pb.separation")
	proto.RegisterType((*NetworkOperator)(nil), "pb.networkOperator")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x34, 0xb5, 0x66, 0x5a, 0x62, 0x1c, 0x10, 0x72, 0x0c, 0x05, 0xa1, 0x14, 0xc9,
	0x41, 0x5f, 0xa1, 0x1e, 0x0a, 0x5a, 0x25, 0xd8, 0x07, 0xd8, 0xc4, 0x55, 0x97, 0xa6, 0x3b, 0xc3,
	0xec, 0x42, 0xc9, 0xdb, 0x4b, 0x37, 0x0a, 0xd6, 0xdb, 0x3f, 0x1f, 0xdf, 0x3f, 0x03, 0x03, 0xf3,
	0x96, 0x0e, 0x07, 0xb2, 0x15, 0x0b, 0x79, 0xc2, 0x98, 0x9b, 0xc5, 0x1a, 0xc0, 0x69, 0x56, 0xa2,
	0xbc, 0x21, 0x8b, 0x19, 0xc4, 0x86, 0x8b, 0xa8, 0x8c, 0x96, 0x69, 0x1d, 0x1b, 0x46, 0x84, 0x84,
	0x49, 0x7c, 0x11, 0x97, 0xd1, 0x72, 0x52, 0x87, 0x7c, 0x62, 0x1f, 0x9d, 0xfa, 0x2c, 0xc6, 0xc1,
	0x0a, 0x79, 0xa1, 0xe0, 0xca, 0x6a, 0x7f, 0x24, 0xd9, 0xbf, 0xb0, 0x16, 0xe5, 0x49, 0xf0, 0x0e,
	0xa6, 0x14, 0xb2, 0x0e, 0xfb, 0xb2, 0x7b, 0xac, 0xb8, 0xa9, 0xce, 0x2c, 0x5d, 0xff, 0x2a, 0x58,
	0xc2, 0x8c, 0x85, 0x1a, 0xd5, 0x98, 0xce, 0xf8, 0xfe, 0xe7, 0xde, 0x5f, 0xb4, 0xba, 0x85, 0xec,
	0xbc, 0x8c, 0x29, 0x4c, 0xd6, 0xba, 0x53, 0x7d, 0x3e, 0xc2, 0x4b, 0x48, 0x9e, 0xc8, 0xb9, 0x3c,
	0x5a, 0x19, 0x48, 0x1f, 0x45, 0x48, 0xde, 0x7a, 0xd6, 0x98, 0xc3, 0x7c, 0x67, 0xf7, 0x96, 0x8e,
	0x36, 0xb0, 0x7c, 0x84, 0x08, 0xd9, 0xc6, 0xbe, 0x0a, 0xb5, 0xda, 0xb9, 0x81, 0x45, 0x38, 0x83,
	0xe9, 0x96, 0x86, 0x21, 0xc6, 0x1b, 0xb8, 0xde, 0x92, 0xff, 0xe7, 0x8c, 0x4f, 0xbd, 0x9d, 0x7d,
	0x56, 0xbe, 0xfd, 0xda, 0xbc, 0x0f, 0x2c, 0x69, 0x2e, 0xc2, 0x17, 0x1f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x35, 0xdd, 0x13, 0x5a, 0x55, 0x01, 0x00, 0x00,
}
