// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareReq) Reset()         { *m = PrepareReq{} }
func (m *PrepareReq) String() string { return proto.CompactTextString(m) }
func (*PrepareReq) ProtoMessage()    {}
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *PrepareReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareReq.Unmarshal(m, b)
}
func (m *PrepareReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareReq.Marshal(b, m, deterministic)
}
func (m *PrepareReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareReq.Merge(m, src)
}
func (m *PrepareReq) XXX_Size() int {
	return xxx_messageInfo_PrepareReq.Size(m)
}
func (m *PrepareReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareReq proto.InternalMessageInfo

type PrepareResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareResp) Reset()         { *m = PrepareResp{} }
func (m *PrepareResp) String() string { return proto.CompactTextString(m) }
func (*PrepareResp) ProtoMessage()    {}
func (*PrepareResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *PrepareResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareResp.Unmarshal(m, b)
}
func (m *PrepareResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareResp.Marshal(b, m, deterministic)
}
func (m *PrepareResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareResp.Merge(m, src)
}
func (m *PrepareResp) XXX_Size() int {
	return xxx_messageInfo_PrepareResp.Size(m)
}
func (m *PrepareResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareResp.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareResp proto.InternalMessageInfo

func (m *PrepareResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type RevokeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeReq) Reset()         { *m = RevokeReq{} }
func (m *RevokeReq) String() string { return proto.CompactTextString(m) }
func (*RevokeReq) ProtoMessage()    {}
func (*RevokeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *RevokeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeReq.Unmarshal(m, b)
}
func (m *RevokeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeReq.Marshal(b, m, deterministic)
}
func (m *RevokeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeReq.Merge(m, src)
}
func (m *RevokeReq) XXX_Size() int {
	return xxx_messageInfo_RevokeReq.Size(m)
}
func (m *RevokeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeReq proto.InternalMessageInfo

type RevokeResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeResp) Reset()         { *m = RevokeResp{} }
func (m *RevokeResp) String() string { return proto.CompactTextString(m) }
func (*RevokeResp) ProtoMessage()    {}
func (*RevokeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *RevokeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeResp.Unmarshal(m, b)
}
func (m *RevokeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeResp.Marshal(b, m, deterministic)
}
func (m *RevokeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeResp.Merge(m, src)
}
func (m *RevokeResp) XXX_Size() int {
	return xxx_messageInfo_RevokeResp.Size(m)
}
func (m *RevokeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeResp proto.InternalMessageInfo

func (m *RevokeResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type RandomInjectReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomInjectReq) Reset()         { *m = RandomInjectReq{} }
func (m *RandomInjectReq) String() string { return proto.CompactTextString(m) }
func (*RandomInjectReq) ProtoMessage()    {}
func (*RandomInjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *RandomInjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomInjectReq.Unmarshal(m, b)
}
func (m *RandomInjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomInjectReq.Marshal(b, m, deterministic)
}
func (m *RandomInjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomInjectReq.Merge(m, src)
}
func (m *RandomInjectReq) XXX_Size() int {
	return xxx_messageInfo_RandomInjectReq.Size(m)
}
func (m *RandomInjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomInjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_RandomInjectReq proto.InternalMessageInfo

type RandomInjectResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomInjectResp) Reset()         { *m = RandomInjectResp{} }
func (m *RandomInjectResp) String() string { return proto.CompactTextString(m) }
func (*RandomInjectResp) ProtoMessage()    {}
func (*RandomInjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *RandomInjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomInjectResp.Unmarshal(m, b)
}
func (m *RandomInjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomInjectResp.Marshal(b, m, deterministic)
}
func (m *RandomInjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomInjectResp.Merge(m, src)
}
func (m *RandomInjectResp) XXX_Size() int {
	return xxx_messageInfo_RandomInjectResp.Size(m)
}
func (m *RandomInjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomInjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_RandomInjectResp proto.InternalMessageInfo

func (m *RandomInjectResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type NetworkOperateReq struct {
	Separation           []*Separation    `protobuf:"bytes,1,rep,name=separation,proto3" json:"separation,omitempty"`
	Operator             *NetworkOperator `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NetworkOperateReq) Reset()         { *m = NetworkOperateReq{} }
func (m *NetworkOperateReq) String() string { return proto.CompactTextString(m) }
func (*NetworkOperateReq) ProtoMessage()    {}
func (*NetworkOperateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *NetworkOperateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkOperateReq.Unmarshal(m, b)
}
func (m *NetworkOperateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkOperateReq.Marshal(b, m, deterministic)
}
func (m *NetworkOperateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkOperateReq.Merge(m, src)
}
func (m *NetworkOperateReq) XXX_Size() int {
	return xxx_messageInfo_NetworkOperateReq.Size(m)
}
func (m *NetworkOperateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkOperateReq.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkOperateReq proto.InternalMessageInfo

func (m *NetworkOperateReq) GetSeparation() []*Separation {
	if m != nil {
		return m.Separation
	}
	return nil
}

func (m *NetworkOperateReq) GetOperator() *NetworkOperator {
	if m != nil {
		return m.Operator
	}
	return nil
}

type NetworkOperateResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Mark                 int32    `protobuf:"varint,2,opt,name=mark,proto3" json:"mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkOperateResp) Reset()         { *m = NetworkOperateResp{} }
func (m *NetworkOperateResp) String() string { return proto.CompactTextString(m) }
func (*NetworkOperateResp) ProtoMessage()    {}
func (*NetworkOperateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{7}
}

func (m *NetworkOperateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkOperateResp.Unmarshal(m, b)
}
func (m *NetworkOperateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkOperateResp.Marshal(b, m, deterministic)
}
func (m *NetworkOperateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkOperateResp.Merge(m, src)
}
func (m *NetworkOperateResp) XXX_Size() int {
	return xxx_messageInfo_NetworkOperateResp.Size(m)
}
func (m *NetworkOperateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkOperateResp.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkOperateResp proto.InternalMessageInfo

func (m *NetworkOperateResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *NetworkOperateResp) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

type RevokeNetworkOperateReq struct {
	Mark                 int32    `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeNetworkOperateReq) Reset()         { *m = RevokeNetworkOperateReq{} }
func (m *RevokeNetworkOperateReq) String() string { return proto.CompactTextString(m) }
func (*RevokeNetworkOperateReq) ProtoMessage()    {}
func (*RevokeNetworkOperateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{8}
}

func (m *RevokeNetworkOperateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeNetworkOperateReq.Unmarshal(m, b)
}
func (m *RevokeNetworkOperateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeNetworkOperateReq.Marshal(b, m, deterministic)
}
func (m *RevokeNetworkOperateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeNetworkOperateReq.Merge(m, src)
}
func (m *RevokeNetworkOperateReq) XXX_Size() int {
	return xxx_messageInfo_RevokeNetworkOperateReq.Size(m)
}
func (m *RevokeNetworkOperateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeNetworkOperateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeNetworkOperateReq proto.InternalMessageInfo

func (m *RevokeNetworkOperateReq) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

type RevokeNetworkOperateResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeNetworkOperateResp) Reset()         { *m = RevokeNetworkOperateResp{} }
func (m *RevokeNetworkOperateResp) String() string { return proto.CompactTextString(m) }
func (*RevokeNetworkOperateResp) ProtoMessage()    {}
func (*RevokeNetworkOperateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{9}
}

func (m *RevokeNetworkOperateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeNetworkOperateResp.Unmarshal(m, b)
}
func (m *RevokeNetworkOperateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeNetworkOperateResp.Marshal(b, m, deterministic)
}
func (m *RevokeNetworkOperateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeNetworkOperateResp.Merge(m, src)
}
func (m *RevokeNetworkOperateResp) XXX_Size() int {
	return xxx_messageInfo_RevokeNetworkOperateResp.Size(m)
}
func (m *RevokeNetworkOperateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeNetworkOperateResp.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeNetworkOperateResp proto.InternalMessageInfo

func (m *RevokeNetworkOperateResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*PrepareReq)(nil), "pb.prepareReq")
	proto.RegisterType((*PrepareResp)(nil), "pb.prepareResp")
	proto.RegisterType((*RevokeReq)(nil), "pb.revokeReq")
	proto.RegisterType((*RevokeResp)(nil), "pb.revokeResp")
	proto.RegisterType((*RandomInjectReq)(nil), "pb.randomInjectReq")
	proto.RegisterType((*RandomInjectResp)(nil), "pb.randomInjectResp")
	proto.RegisterType((*NetworkOperateReq)(nil), "pb.networkOperateReq")
	proto.RegisterType((*NetworkOperateResp)(nil), "pb.networkOperateResp")
	proto.RegisterType((*RevokeNetworkOperateReq)(nil), "pb.revokeNetworkOperateReq")
	proto.RegisterType((*RevokeNetworkOperateResp)(nil), "pb.revokeNetworkOperateResp")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x4f, 0xb3, 0x40,
	0x10, 0x7e, 0xe9, 0xab, 0xb5, 0x0e, 0xd8, 0xda, 0xb1, 0x56, 0x82, 0x1e, 0x1a, 0xa2, 0x49, 0x35,
	0x8a, 0x09, 0x1e, 0xbd, 0xe8, 0xd1, 0x83, 0x9a, 0xe0, 0x2f, 0xd8, 0xd6, 0x3d, 0x68, 0x85, 0x5d,
	0x87, 0x55, 0xff, 0x99, 0xbf, 0xcf, 0xec, 0xf4, 0x0b, 0x4a, 0xe9, 0x8d, 0x99, 0x7d, 0x3e, 0x26,
	0xcf, 0x13, 0xc0, 0x4b, 0x45, 0x6e, 0x24, 0x45, 0x9a, 0x94, 0x51, 0xd8, 0xd0, 0xa3, 0xc0, 0x1b,
	0xab, 0x34, 0x55, 0xd9, 0x74, 0x13, 0x7a, 0x00, 0x9a, 0xa4, 0x16, 0x24, 0x13, 0xf9, 0x19, 0x9e,
	0x81, 0xbb, 0x98, 0x72, 0x8d, 0x7d, 0x68, 0x92, 0xcc, 0xbf, 0x3e, 0x8c, 0xef, 0x0c, 0x9c, 0x61,
	0x2b, 0x99, 0x4d, 0xa1, 0x0b, 0xbb, 0x24, 0xbf, 0xd5, 0x84, 0x39, 0xa7, 0x00, 0xf3, 0x61, 0x03,
	0xa5, 0x0b, 0x1d, 0x12, 0xd9, 0xab, 0x4a, 0x1f, 0xb2, 0x77, 0x39, 0x36, 0x96, 0x78, 0x01, 0xfb,
	0xe5, 0xd5, 0x06, 0xba, 0x81, 0x6e, 0x26, 0xcd, 0x8f, 0xa2, 0xc9, 0xb3, 0x96, 0x24, 0x8c, 0x75,
	0xc6, 0x08, 0x20, 0xb7, 0xc7, 0x0a, 0xf3, 0xa6, 0x32, 0xdf, 0x19, 0xfc, 0x1f, 0xba, 0x71, 0x3b,
	0xd2, 0xa3, 0x68, 0xb9, 0x4d, 0x0a, 0x08, 0xbc, 0x86, 0x96, 0x62, 0xb6, 0x22, 0xbf, 0x31, 0x70,
	0x86, 0x6e, 0x7c, 0x60, 0xd1, 0x25, 0x61, 0x45, 0xc9, 0x02, 0x14, 0xde, 0x01, 0xae, 0xba, 0xd6,
	0xdf, 0x88, 0x08, 0x5b, 0xa9, 0xa0, 0x09, 0x4b, 0x6f, 0x27, 0xfc, 0x1d, 0x5e, 0xc1, 0xd1, 0x34,
	0x9c, 0xa7, 0xca, 0xf5, 0x73, 0xb8, 0x53, 0x80, 0xc7, 0xe0, 0xaf, 0x87, 0xd7, 0xdb, 0xc6, 0xbf,
	0x0d, 0x68, 0x3e, 0x72, 0xc9, 0x78, 0x09, 0x3b, 0xb3, 0xfa, 0x90, 0x73, 0x58, 0x36, 0x1b, 0x74,
	0x4a, 0x73, 0xae, 0xc3, 0x7f, 0x78, 0x6e, 0x05, 0xad, 0x19, 0xee, 0xd9, 0xc7, 0x45, 0xa3, 0x41,
	0xbb, 0x38, 0x32, 0xf4, 0x16, 0xbc, 0x62, 0x55, 0xc8, 0xb9, 0xad, 0xf4, 0x19, 0xf4, 0xaa, 0x4b,
	0x26, 0xdf, 0x43, 0xbb, 0x9c, 0x22, 0x1e, 0x56, 0x62, 0x67, 0xdf, 0xfe, 0xba, 0x35, 0x4b, 0xbc,
	0x40, 0x6f, 0x5d, 0x2e, 0x78, 0xbc, 0xbc, 0xb4, 0x12, 0x70, 0x70, 0x52, 0xff, 0x68, 0x45, 0x47,
	0x4d, 0xfe, 0x03, 0x6e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x15, 0x23, 0x28, 0x23, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PrepareResp, error)
	Revoke(ctx context.Context, in *RevokeReq, opts ...grpc.CallOption) (*RevokeResp, error)
	RandomInject(ctx context.Context, in *RandomInjectReq, opts ...grpc.CallOption) (*RandomInjectResp, error)
	NetworkOperate(ctx context.Context, in *NetworkOperateReq, opts ...grpc.CallOption) (*NetworkOperateResp, error)
	RevokeNetworkOperate(ctx context.Context, in *RevokeNetworkOperateReq, opts ...grpc.CallOption) (*RevokeNetworkOperateResp, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Prepare(ctx context.Context, in *PrepareReq, opts ...grpc.CallOption) (*PrepareResp, error) {
	out := new(PrepareResp)
	err := c.cc.Invoke(ctx, "/pb.Master/prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) Revoke(ctx context.Context, in *RevokeReq, opts ...grpc.CallOption) (*RevokeResp, error) {
	out := new(RevokeResp)
	err := c.cc.Invoke(ctx, "/pb.Master/revoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) RandomInject(ctx context.Context, in *RandomInjectReq, opts ...grpc.CallOption) (*RandomInjectResp, error) {
	out := new(RandomInjectResp)
	err := c.cc.Invoke(ctx, "/pb.Master/randomInject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) NetworkOperate(ctx context.Context, in *NetworkOperateReq, opts ...grpc.CallOption) (*NetworkOperateResp, error) {
	out := new(NetworkOperateResp)
	err := c.cc.Invoke(ctx, "/pb.Master/networkOperate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) RevokeNetworkOperate(ctx context.Context, in *RevokeNetworkOperateReq, opts ...grpc.CallOption) (*RevokeNetworkOperateResp, error) {
	out := new(RevokeNetworkOperateResp)
	err := c.cc.Invoke(ctx, "/pb.Master/revokeNetworkOperate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Prepare(context.Context, *PrepareReq) (*PrepareResp, error)
	Revoke(context.Context, *RevokeReq) (*RevokeResp, error)
	RandomInject(context.Context, *RandomInjectReq) (*RandomInjectResp, error)
	NetworkOperate(context.Context, *NetworkOperateReq) (*NetworkOperateResp, error)
	RevokeNetworkOperate(context.Context, *RevokeNetworkOperateReq) (*RevokeNetworkOperateResp, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) Prepare(ctx context.Context, req *PrepareReq) (*PrepareResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedMasterServer) Revoke(ctx context.Context, req *RevokeReq) (*RevokeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (*UnimplementedMasterServer) RandomInject(ctx context.Context, req *RandomInjectReq) (*RandomInjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomInject not implemented")
}
func (*UnimplementedMasterServer) NetworkOperate(ctx context.Context, req *NetworkOperateReq) (*NetworkOperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkOperate not implemented")
}
func (*UnimplementedMasterServer) RevokeNetworkOperate(ctx context.Context, req *RevokeNetworkOperateReq) (*RevokeNetworkOperateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeNetworkOperate not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Prepare(ctx, req.(*PrepareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/Revoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Revoke(ctx, req.(*RevokeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_RandomInject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomInjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RandomInject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/RandomInject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RandomInject(ctx, req.(*RandomInjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_NetworkOperate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkOperateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).NetworkOperate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/NetworkOperate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).NetworkOperate(ctx, req.(*NetworkOperateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_RevokeNetworkOperate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeNetworkOperateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RevokeNetworkOperate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/RevokeNetworkOperate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RevokeNetworkOperate(ctx, req.(*RevokeNetworkOperateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "prepare",
			Handler:    _Master_Prepare_Handler,
		},
		{
			MethodName: "revoke",
			Handler:    _Master_Revoke_Handler,
		},
		{
			MethodName: "randomInject",
			Handler:    _Master_RandomInject_Handler,
		},
		{
			MethodName: "networkOperate",
			Handler:    _Master_NetworkOperate_Handler,
		},
		{
			MethodName: "revokeNetworkOperate",
			Handler:    _Master_RevokeNetworkOperate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
