// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareMasterReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareMasterReq) Reset()         { *m = PrepareMasterReq{} }
func (m *PrepareMasterReq) String() string { return proto.CompactTextString(m) }
func (*PrepareMasterReq) ProtoMessage()    {}
func (*PrepareMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *PrepareMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareMasterReq.Unmarshal(m, b)
}
func (m *PrepareMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareMasterReq.Marshal(b, m, deterministic)
}
func (m *PrepareMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareMasterReq.Merge(m, src)
}
func (m *PrepareMasterReq) XXX_Size() int {
	return xxx_messageInfo_PrepareMasterReq.Size(m)
}
func (m *PrepareMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareMasterReq proto.InternalMessageInfo

type PrepareMasterResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareMasterResp) Reset()         { *m = PrepareMasterResp{} }
func (m *PrepareMasterResp) String() string { return proto.CompactTextString(m) }
func (*PrepareMasterResp) ProtoMessage()    {}
func (*PrepareMasterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *PrepareMasterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareMasterResp.Unmarshal(m, b)
}
func (m *PrepareMasterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareMasterResp.Marshal(b, m, deterministic)
}
func (m *PrepareMasterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareMasterResp.Merge(m, src)
}
func (m *PrepareMasterResp) XXX_Size() int {
	return xxx_messageInfo_PrepareMasterResp.Size(m)
}
func (m *PrepareMasterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareMasterResp.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareMasterResp proto.InternalMessageInfo

func (m *PrepareMasterResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type RevokeMasterReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeMasterReq) Reset()         { *m = RevokeMasterReq{} }
func (m *RevokeMasterReq) String() string { return proto.CompactTextString(m) }
func (*RevokeMasterReq) ProtoMessage()    {}
func (*RevokeMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *RevokeMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeMasterReq.Unmarshal(m, b)
}
func (m *RevokeMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeMasterReq.Marshal(b, m, deterministic)
}
func (m *RevokeMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeMasterReq.Merge(m, src)
}
func (m *RevokeMasterReq) XXX_Size() int {
	return xxx_messageInfo_RevokeMasterReq.Size(m)
}
func (m *RevokeMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeMasterReq proto.InternalMessageInfo

type RevokeMasterResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeMasterResp) Reset()         { *m = RevokeMasterResp{} }
func (m *RevokeMasterResp) String() string { return proto.CompactTextString(m) }
func (*RevokeMasterResp) ProtoMessage()    {}
func (*RevokeMasterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *RevokeMasterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeMasterResp.Unmarshal(m, b)
}
func (m *RevokeMasterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeMasterResp.Marshal(b, m, deterministic)
}
func (m *RevokeMasterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeMasterResp.Merge(m, src)
}
func (m *RevokeMasterResp) XXX_Size() int {
	return xxx_messageInfo_RevokeMasterResp.Size(m)
}
func (m *RevokeMasterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeMasterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeMasterResp proto.InternalMessageInfo

func (m *RevokeMasterResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TwoSplitReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoSplitReq) Reset()         { *m = TwoSplitReq{} }
func (m *TwoSplitReq) String() string { return proto.CompactTextString(m) }
func (*TwoSplitReq) ProtoMessage()    {}
func (*TwoSplitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *TwoSplitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoSplitReq.Unmarshal(m, b)
}
func (m *TwoSplitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoSplitReq.Marshal(b, m, deterministic)
}
func (m *TwoSplitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoSplitReq.Merge(m, src)
}
func (m *TwoSplitReq) XXX_Size() int {
	return xxx_messageInfo_TwoSplitReq.Size(m)
}
func (m *TwoSplitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoSplitReq.DiscardUnknown(m)
}

var xxx_messageInfo_TwoSplitReq proto.InternalMessageInfo

type TwoSplitResp struct {
	Result               bool                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	NetworkOperateMark   []*NetworkOperateMark `protobuf:"bytes,2,rep,name=networkOperateMark,proto3" json:"networkOperateMark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TwoSplitResp) Reset()         { *m = TwoSplitResp{} }
func (m *TwoSplitResp) String() string { return proto.CompactTextString(m) }
func (*TwoSplitResp) ProtoMessage()    {}
func (*TwoSplitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *TwoSplitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoSplitResp.Unmarshal(m, b)
}
func (m *TwoSplitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoSplitResp.Marshal(b, m, deterministic)
}
func (m *TwoSplitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoSplitResp.Merge(m, src)
}
func (m *TwoSplitResp) XXX_Size() int {
	return xxx_messageInfo_TwoSplitResp.Size(m)
}
func (m *TwoSplitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoSplitResp.DiscardUnknown(m)
}

var xxx_messageInfo_TwoSplitResp proto.InternalMessageInfo

func (m *TwoSplitResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *TwoSplitResp) GetNetworkOperateMark() []*NetworkOperateMark {
	if m != nil {
		return m.NetworkOperateMark
	}
	return nil
}

type RandomInjectReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomInjectReq) Reset()         { *m = RandomInjectReq{} }
func (m *RandomInjectReq) String() string { return proto.CompactTextString(m) }
func (*RandomInjectReq) ProtoMessage()    {}
func (*RandomInjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *RandomInjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomInjectReq.Unmarshal(m, b)
}
func (m *RandomInjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomInjectReq.Marshal(b, m, deterministic)
}
func (m *RandomInjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomInjectReq.Merge(m, src)
}
func (m *RandomInjectReq) XXX_Size() int {
	return xxx_messageInfo_RandomInjectReq.Size(m)
}
func (m *RandomInjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomInjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_RandomInjectReq proto.InternalMessageInfo

type RandomInjectResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomInjectResp) Reset()         { *m = RandomInjectResp{} }
func (m *RandomInjectResp) String() string { return proto.CompactTextString(m) }
func (*RandomInjectResp) ProtoMessage()    {}
func (*RandomInjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{7}
}

func (m *RandomInjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomInjectResp.Unmarshal(m, b)
}
func (m *RandomInjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomInjectResp.Marshal(b, m, deterministic)
}
func (m *RandomInjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomInjectResp.Merge(m, src)
}
func (m *RandomInjectResp) XXX_Size() int {
	return xxx_messageInfo_RandomInjectResp.Size(m)
}
func (m *RandomInjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomInjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_RandomInjectResp proto.InternalMessageInfo

func (m *RandomInjectResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type IsolateNodeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsolateNodeReq) Reset()         { *m = IsolateNodeReq{} }
func (m *IsolateNodeReq) String() string { return proto.CompactTextString(m) }
func (*IsolateNodeReq) ProtoMessage()    {}
func (*IsolateNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{8}
}

func (m *IsolateNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsolateNodeReq.Unmarshal(m, b)
}
func (m *IsolateNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsolateNodeReq.Marshal(b, m, deterministic)
}
func (m *IsolateNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsolateNodeReq.Merge(m, src)
}
func (m *IsolateNodeReq) XXX_Size() int {
	return xxx_messageInfo_IsolateNodeReq.Size(m)
}
func (m *IsolateNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IsolateNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_IsolateNodeReq proto.InternalMessageInfo

type IsolateNodeResp struct {
	Result               bool                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	NetworkOperateMark   []*NetworkOperateMark `protobuf:"bytes,2,rep,name=networkOperateMark,proto3" json:"networkOperateMark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IsolateNodeResp) Reset()         { *m = IsolateNodeResp{} }
func (m *IsolateNodeResp) String() string { return proto.CompactTextString(m) }
func (*IsolateNodeResp) ProtoMessage()    {}
func (*IsolateNodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{9}
}

func (m *IsolateNodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsolateNodeResp.Unmarshal(m, b)
}
func (m *IsolateNodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsolateNodeResp.Marshal(b, m, deterministic)
}
func (m *IsolateNodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsolateNodeResp.Merge(m, src)
}
func (m *IsolateNodeResp) XXX_Size() int {
	return xxx_messageInfo_IsolateNodeResp.Size(m)
}
func (m *IsolateNodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IsolateNodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_IsolateNodeResp proto.InternalMessageInfo

func (m *IsolateNodeResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *IsolateNodeResp) GetNetworkOperateMark() []*NetworkOperateMark {
	if m != nil {
		return m.NetworkOperateMark
	}
	return nil
}

type NetworkOperateMasterReq struct {
	NetworkOperateMark   []*NetworkOperateMark `protobuf:"bytes,1,rep,name=networkOperateMark,proto3" json:"networkOperateMark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NetworkOperateMasterReq) Reset()         { *m = NetworkOperateMasterReq{} }
func (m *NetworkOperateMasterReq) String() string { return proto.CompactTextString(m) }
func (*NetworkOperateMasterReq) ProtoMessage()    {}
func (*NetworkOperateMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{10}
}

func (m *NetworkOperateMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkOperateMasterReq.Unmarshal(m, b)
}
func (m *NetworkOperateMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkOperateMasterReq.Marshal(b, m, deterministic)
}
func (m *NetworkOperateMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkOperateMasterReq.Merge(m, src)
}
func (m *NetworkOperateMasterReq) XXX_Size() int {
	return xxx_messageInfo_NetworkOperateMasterReq.Size(m)
}
func (m *NetworkOperateMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkOperateMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkOperateMasterReq proto.InternalMessageInfo

func (m *NetworkOperateMasterReq) GetNetworkOperateMark() []*NetworkOperateMark {
	if m != nil {
		return m.NetworkOperateMark
	}
	return nil
}

type NetworkOperateMasterResp struct {
	Result               bool                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	NetworkOperateMark   []*NetworkOperateMark `protobuf:"bytes,2,rep,name=networkOperateMark,proto3" json:"networkOperateMark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NetworkOperateMasterResp) Reset()         { *m = NetworkOperateMasterResp{} }
func (m *NetworkOperateMasterResp) String() string { return proto.CompactTextString(m) }
func (*NetworkOperateMasterResp) ProtoMessage()    {}
func (*NetworkOperateMasterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{11}
}

func (m *NetworkOperateMasterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkOperateMasterResp.Unmarshal(m, b)
}
func (m *NetworkOperateMasterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkOperateMasterResp.Marshal(b, m, deterministic)
}
func (m *NetworkOperateMasterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkOperateMasterResp.Merge(m, src)
}
func (m *NetworkOperateMasterResp) XXX_Size() int {
	return xxx_messageInfo_NetworkOperateMasterResp.Size(m)
}
func (m *NetworkOperateMasterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkOperateMasterResp.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkOperateMasterResp proto.InternalMessageInfo

func (m *NetworkOperateMasterResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *NetworkOperateMasterResp) GetNetworkOperateMark() []*NetworkOperateMark {
	if m != nil {
		return m.NetworkOperateMark
	}
	return nil
}

type NetworkRevokeOperateMasterReq struct {
	IpMarks              []string `protobuf:"bytes,1,rep,name=ipMarks,proto3" json:"ipMarks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkRevokeOperateMasterReq) Reset()         { *m = NetworkRevokeOperateMasterReq{} }
func (m *NetworkRevokeOperateMasterReq) String() string { return proto.CompactTextString(m) }
func (*NetworkRevokeOperateMasterReq) ProtoMessage()    {}
func (*NetworkRevokeOperateMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{12}
}

func (m *NetworkRevokeOperateMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkRevokeOperateMasterReq.Unmarshal(m, b)
}
func (m *NetworkRevokeOperateMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkRevokeOperateMasterReq.Marshal(b, m, deterministic)
}
func (m *NetworkRevokeOperateMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkRevokeOperateMasterReq.Merge(m, src)
}
func (m *NetworkRevokeOperateMasterReq) XXX_Size() int {
	return xxx_messageInfo_NetworkRevokeOperateMasterReq.Size(m)
}
func (m *NetworkRevokeOperateMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkRevokeOperateMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkRevokeOperateMasterReq proto.InternalMessageInfo

func (m *NetworkRevokeOperateMasterReq) GetIpMarks() []string {
	if m != nil {
		return m.IpMarks
	}
	return nil
}

type NetworkRevokeOperateMasterResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkRevokeOperateMasterResp) Reset()         { *m = NetworkRevokeOperateMasterResp{} }
func (m *NetworkRevokeOperateMasterResp) String() string { return proto.CompactTextString(m) }
func (*NetworkRevokeOperateMasterResp) ProtoMessage()    {}
func (*NetworkRevokeOperateMasterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{13}
}

func (m *NetworkRevokeOperateMasterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkRevokeOperateMasterResp.Unmarshal(m, b)
}
func (m *NetworkRevokeOperateMasterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkRevokeOperateMasterResp.Marshal(b, m, deterministic)
}
func (m *NetworkRevokeOperateMasterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkRevokeOperateMasterResp.Merge(m, src)
}
func (m *NetworkRevokeOperateMasterResp) XXX_Size() int {
	return xxx_messageInfo_NetworkRevokeOperateMasterResp.Size(m)
}
func (m *NetworkRevokeOperateMasterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkRevokeOperateMasterResp.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkRevokeOperateMasterResp proto.InternalMessageInfo

func (m *NetworkRevokeOperateMasterResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*PrepareMasterReq)(nil), "pb.prepareMasterReq")
	proto.RegisterType((*PrepareMasterResp)(nil), "pb.prepareMasterResp")
	proto.RegisterType((*RevokeMasterReq)(nil), "pb.revokeMasterReq")
	proto.RegisterType((*RevokeMasterResp)(nil), "pb.revokeMasterResp")
	proto.RegisterType((*TwoSplitReq)(nil), "pb.twoSplitReq")
	proto.RegisterType((*TwoSplitResp)(nil), "pb.twoSplitResp")
	proto.RegisterType((*RandomInjectReq)(nil), "pb.randomInjectReq")
	proto.RegisterType((*RandomInjectResp)(nil), "pb.randomInjectResp")
	proto.RegisterType((*IsolateNodeReq)(nil), "pb.isolateNodeReq")
	proto.RegisterType((*IsolateNodeResp)(nil), "pb.isolateNodeResp")
	proto.RegisterType((*NetworkOperateMasterReq)(nil), "pb.networkOperateMasterReq")
	proto.RegisterType((*NetworkOperateMasterResp)(nil), "pb.networkOperateMasterResp")
	proto.RegisterType((*NetworkRevokeOperateMasterReq)(nil), "pb.networkRevokeOperateMasterReq")
	proto.RegisterType((*NetworkRevokeOperateMasterResp)(nil), "pb.networkRevokeOperateMasterResp")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x0e, 0xd2, 0x30,
	0x14, 0xc6, 0xf9, 0x93, 0x00, 0x1e, 0x26, 0x8c, 0x82, 0xb8, 0x4c, 0x34, 0xb8, 0x2b, 0xa2, 0xc9,
	0x4c, 0x30, 0x26, 0x18, 0xef, 0xbc, 0x30, 0xf1, 0x02, 0x4c, 0xe6, 0x03, 0x98, 0x6e, 0x34, 0x32,
	0x61, 0x6b, 0xe9, 0x0a, 0x24, 0xbc, 0xa5, 0x6f, 0x64, 0x5a, 0xb6, 0xb8, 0xee, 0x0f, 0xc6, 0x1b,
	0x2e, 0xfb, 0xed, 0xfb, 0xf5, 0x9c, 0x43, 0xbf, 0x03, 0x18, 0x11, 0x4e, 0x04, 0xe1, 0x2e, 0xe3,
	0x54, 0x50, 0xd4, 0x62, 0xbe, 0x6d, 0x04, 0x34, 0x8a, 0x68, 0x7c, 0x53, 0x1c, 0x04, 0x26, 0xe3,
	0x84, 0x61, 0x4e, 0xd6, 0xca, 0xe8, 0x91, 0xa3, 0xf3, 0x16, 0x46, 0x05, 0x2d, 0x61, 0x68, 0x0a,
	0x1d, 0x4e, 0x92, 0xd3, 0x41, 0x58, 0xcd, 0x79, 0x73, 0xd1, 0xf3, 0xd2, 0x93, 0x33, 0x82, 0x21,
	0x27, 0x67, 0xba, 0xcf, 0xf1, 0x6f, 0xc0, 0xd4, 0xa5, 0x3b, 0xf8, 0x53, 0xe8, 0x8b, 0x0b, 0xfd,
	0xce, 0x0e, 0xa1, 0x90, 0x68, 0x0c, 0xc6, 0xdf, 0x63, 0x3d, 0x86, 0xbe, 0x00, 0x8a, 0x89, 0xb8,
	0x50, 0xbe, 0xff, 0xc6, 0x08, 0xc7, 0x82, 0xac, 0x31, 0xdf, 0x5b, 0xad, 0x79, 0x7b, 0xd1, 0x5f,
	0x4e, 0x5d, 0xe6, 0xbb, 0xe5, 0xaf, 0x5e, 0x05, 0xa1, 0xba, 0xc7, 0xf1, 0x96, 0x46, 0x5f, 0xe3,
	0x5f, 0x24, 0x10, 0x59, 0xf7, 0x9a, 0x74, 0xa7, 0x7b, 0x13, 0x06, 0x61, 0x42, 0x0f, 0x58, 0x90,
	0x0d, 0xdd, 0x12, 0x49, 0x1f, 0x61, 0xa8, 0x29, 0x0f, 0x98, 0x01, 0xc3, 0xf3, 0xa2, 0x9a, 0xbe,
	0x44, 0x4d, 0x89, 0xe6, 0x7f, 0x97, 0xb8, 0x82, 0x55, 0x5d, 0xe2, 0x01, 0xe3, 0x7d, 0x84, 0x97,
	0xa9, 0xea, 0xa9, 0x50, 0x95, 0x86, 0xb4, 0xa0, 0x1b, 0x32, 0x69, 0x4d, 0xd4, 0x64, 0x4f, 0xbc,
	0xec, 0xe8, 0xac, 0xe0, 0xd5, 0x3d, 0xb4, 0xbe, 0xf9, 0xe5, 0xef, 0x36, 0x74, 0x6e, 0x36, 0xb4,
	0x82, 0x6e, 0xba, 0x0d, 0x68, 0x22, 0xdb, 0x2e, 0xae, 0x8b, 0xfd, 0xac, 0x42, 0x4d, 0x98, 0xd3,
	0x40, 0x1f, 0xe4, 0xe5, 0xb2, 0x2e, 0x1a, 0x4b, 0x4b, 0x61, 0x4d, 0xec, 0x49, 0x59, 0x54, 0xd8,
	0x27, 0x30, 0xf2, 0x01, 0x4c, 0x61, 0x3d, 0xa5, 0x29, 0x5c, 0xc8, 0xa9, 0xd3, 0x40, 0xef, 0xa0,
	0x97, 0x2d, 0x10, 0x1a, 0x4a, 0x4f, 0x6e, 0xbb, 0x6c, 0x53, 0x17, 0x14, 0xb0, 0x82, 0x7e, 0x2e,
	0xb0, 0x08, 0x49, 0x8b, 0x9e, 0x69, 0x7b, 0x5c, 0xd2, 0x14, 0xb9, 0x86, 0x81, 0xfe, 0x5c, 0xe8,
	0x45, 0xd5, 0xb3, 0x66, 0xe3, 0xce, 0xea, 0x3f, 0xaa, 0xeb, 0x7e, 0xc0, 0xe4, 0xf6, 0x63, 0x6c,
	0xf4, 0x4b, 0x5f, 0xe7, 0xb8, 0xea, 0x04, 0xd8, 0xce, 0xbf, 0x2c, 0xb2, 0xc0, 0xe7, 0x19, 0xd8,
	0x01, 0x8d, 0xdc, 0x9f, 0xa1, 0xd8, 0x9d, 0x7c, 0x97, 0x9c, 0xf1, 0x35, 0xc0, 0x6e, 0xb0, 0xc3,
	0x34, 0x71, 0x99, 0xef, 0x77, 0xd4, 0xff, 0xe1, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb,
	0x0f, 0xf5, 0x12, 0x31, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Prepare(ctx context.Context, in *PrepareMasterReq, opts ...grpc.CallOption) (*PrepareMasterResp, error)
	Revoke(ctx context.Context, in *RevokeMasterReq, opts ...grpc.CallOption) (*RevokeMasterResp, error)
	RandomInject(ctx context.Context, in *RandomInjectReq, opts ...grpc.CallOption) (*RandomInjectResp, error)
	TwoSplit(ctx context.Context, in *TwoSplitReq, opts ...grpc.CallOption) (*TwoSplitResp, error)
	IsolateNode(ctx context.Context, in *IsolateNodeReq, opts ...grpc.CallOption) (*IsolateNodeResp, error)
	NetworkOperate(ctx context.Context, in *NetworkOperateMasterReq, opts ...grpc.CallOption) (*NetworkOperateMasterResp, error)
	RevokeNetworkOperate(ctx context.Context, in *NetworkRevokeOperateMasterReq, opts ...grpc.CallOption) (*NetworkRevokeOperateMasterResp, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Prepare(ctx context.Context, in *PrepareMasterReq, opts ...grpc.CallOption) (*PrepareMasterResp, error) {
	out := new(PrepareMasterResp)
	err := c.cc.Invoke(ctx, "/pb.Master/prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) Revoke(ctx context.Context, in *RevokeMasterReq, opts ...grpc.CallOption) (*RevokeMasterResp, error) {
	out := new(RevokeMasterResp)
	err := c.cc.Invoke(ctx, "/pb.Master/revoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) RandomInject(ctx context.Context, in *RandomInjectReq, opts ...grpc.CallOption) (*RandomInjectResp, error) {
	out := new(RandomInjectResp)
	err := c.cc.Invoke(ctx, "/pb.Master/randomInject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) TwoSplit(ctx context.Context, in *TwoSplitReq, opts ...grpc.CallOption) (*TwoSplitResp, error) {
	out := new(TwoSplitResp)
	err := c.cc.Invoke(ctx, "/pb.Master/twoSplit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) IsolateNode(ctx context.Context, in *IsolateNodeReq, opts ...grpc.CallOption) (*IsolateNodeResp, error) {
	out := new(IsolateNodeResp)
	err := c.cc.Invoke(ctx, "/pb.Master/isolateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) NetworkOperate(ctx context.Context, in *NetworkOperateMasterReq, opts ...grpc.CallOption) (*NetworkOperateMasterResp, error) {
	out := new(NetworkOperateMasterResp)
	err := c.cc.Invoke(ctx, "/pb.Master/networkOperate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) RevokeNetworkOperate(ctx context.Context, in *NetworkRevokeOperateMasterReq, opts ...grpc.CallOption) (*NetworkRevokeOperateMasterResp, error) {
	out := new(NetworkRevokeOperateMasterResp)
	err := c.cc.Invoke(ctx, "/pb.Master/revokeNetworkOperate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Prepare(context.Context, *PrepareMasterReq) (*PrepareMasterResp, error)
	Revoke(context.Context, *RevokeMasterReq) (*RevokeMasterResp, error)
	RandomInject(context.Context, *RandomInjectReq) (*RandomInjectResp, error)
	TwoSplit(context.Context, *TwoSplitReq) (*TwoSplitResp, error)
	IsolateNode(context.Context, *IsolateNodeReq) (*IsolateNodeResp, error)
	NetworkOperate(context.Context, *NetworkOperateMasterReq) (*NetworkOperateMasterResp, error)
	RevokeNetworkOperate(context.Context, *NetworkRevokeOperateMasterReq) (*NetworkRevokeOperateMasterResp, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) Prepare(ctx context.Context, req *PrepareMasterReq) (*PrepareMasterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedMasterServer) Revoke(ctx context.Context, req *RevokeMasterReq) (*RevokeMasterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (*UnimplementedMasterServer) RandomInject(ctx context.Context, req *RandomInjectReq) (*RandomInjectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomInject not implemented")
}
func (*UnimplementedMasterServer) TwoSplit(ctx context.Context, req *TwoSplitReq) (*TwoSplitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoSplit not implemented")
}
func (*UnimplementedMasterServer) IsolateNode(ctx context.Context, req *IsolateNodeReq) (*IsolateNodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsolateNode not implemented")
}
func (*UnimplementedMasterServer) NetworkOperate(ctx context.Context, req *NetworkOperateMasterReq) (*NetworkOperateMasterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkOperate not implemented")
}
func (*UnimplementedMasterServer) RevokeNetworkOperate(ctx context.Context, req *NetworkRevokeOperateMasterReq) (*NetworkRevokeOperateMasterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeNetworkOperate not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Prepare(ctx, req.(*PrepareMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/Revoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Revoke(ctx, req.(*RevokeMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_RandomInject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomInjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RandomInject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/RandomInject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RandomInject(ctx, req.(*RandomInjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_TwoSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoSplitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).TwoSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/TwoSplit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).TwoSplit(ctx, req.(*TwoSplitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_IsolateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsolateNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).IsolateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/IsolateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).IsolateNode(ctx, req.(*IsolateNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_NetworkOperate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkOperateMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).NetworkOperate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/NetworkOperate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).NetworkOperate(ctx, req.(*NetworkOperateMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_RevokeNetworkOperate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRevokeOperateMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RevokeNetworkOperate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/RevokeNetworkOperate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RevokeNetworkOperate(ctx, req.(*NetworkRevokeOperateMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "prepare",
			Handler:    _Master_Prepare_Handler,
		},
		{
			MethodName: "revoke",
			Handler:    _Master_Revoke_Handler,
		},
		{
			MethodName: "randomInject",
			Handler:    _Master_RandomInject_Handler,
		},
		{
			MethodName: "twoSplit",
			Handler:    _Master_TwoSplit_Handler,
		},
		{
			MethodName: "isolateNode",
			Handler:    _Master_IsolateNode_Handler,
		},
		{
			MethodName: "networkOperate",
			Handler:    _Master_NetworkOperate_Handler,
		},
		{
			MethodName: "revokeNetworkOperate",
			Handler:    _Master_RevokeNetworkOperate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
